
version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'    
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  upcoming:
    build: upcoming
    ports:
      - '4000:4000'
    volumes:
      - ./upcoming:/usr/app
      - /usr/app/node_modules
  eventbus:
    build: eventbus
    volumes:
      - ./eventbus:/usr/app
      - /usr/app/node_modules
  query:
    build: query
    ports:
      - '4002:4002'
    volumes:
      - ./query:/usr/app
      - /usr/app/node_modules
  
  events-db:
    image: mongo:latest
    volumes:
      - events-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  events-data: